//random avatar
//
const names = `Ryan Bryant
George Kelly
Susan Alexander
Keith Morris
Deborah Taylor
David Jenkins
Jerry Peterson
Sara Hernandez
Kevin Washington
Harry Walker
Angela Hill
Timothy Adams
Jack Morgan
Steve James
Carl Anderson
Mildred Howard
Harold Brown
Earl Jackson
Peter Long
Kelly Collins
Carolyn Coleman
Douglas Baker
Lillian Mitchell
Gerald Sanders
Scott Price
Eric Campbell
Donna Allen
Alice Butler
Patrick Miller
Martin Hall
Beverly Simmons
Phillip Bailey
Gregory Gray
Steven Brooks
Denise Thompson
Christopher Wright
Fred Henderson
Judith Davis
Chris Cox
William Russell
Theresa Rodriguez
Kathleen Flores
Ruth Bell
Karen Ramirez
Thomas Harris
Virginia Green
Robert Powell
Daniel Stewart
Stephen Roberts
Stephanie Evans
Brian Wilson
Henry Wood
Gloria Jones
Sandra Edwards
Jessica Robinson
Raymond Watson
Brenda Carter
Mark Rivera
Howard Richardson
Adam Lewis
Johnny Young
Matthew Rogers
Rachel Gonzales
Phyllis Turner
Emily Phillips
Marie Lopez
Russell Perez
Norma Patterson
John Martinez
Sean Hughes
Jose Parker
Dennis Bennett
Nancy Barnes
Carlos Murphy
Marilyn Foster
Dorothy King
Martha Torres
Annie Moore
Ralph Perry
Pamela Thomas
Judy Diaz
Tammy Scott
Arthur Lee
Tina Cook
Julie Griffin
Alan Clark
Jennifer White
Bruce Cooper
Jimmy Williams
Ronald Ward
Maria Nelson
Barbara Ross
Jane Sanchez
Anthony Johnson
Jacqueline Reed
Frank Gonzalez
Shirley Smith
Rose Garcia
Billy Martin
Cynthia`;

const namesArray = names.split('\n').map(name => `${name.trim()}`)
const randomIndexName = Math.floor(Math.random() * namesArray.length)
export const randomName = namesArray[randomIndexName]
export const randomAvatarURL = `https://robohash.org/${randomName}`